server:
  port: 8080

spring:
  mvc:
    static-path-pattern: /static/**

  security:
    user:
      name: test@naver.com
      password: 1q2w3e4r!

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-2.cpcocnb0ewp7.ap-northeast-2.rds.amazonaws.com/testdb
    username: admin
    password: 1q2w3e4r!

mybatis:
  mapper-locations:
    - /mappers/*.xml